In [23]:
import numpy as np
#numpy is imported as alias
#in py alias are altered name for refering to the same thing, like in this example numpy package can be referd to as np instead of numpy 

In [24]:
ar1=np.array([1,2,3,4,5])

In [26]:
data2=np.array(5)


In [27]:
data2.ndim

0

In [14]:
ar1

array([1, 2, 3, 4, 5])

In [15]:
ar1.ndim

1

In [16]:
ar2=np.array([[[1,2,3,4,5],[6,7,8,9,10]]])

In [67]:
ar2

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [68]:
ar2.ndim

3

In [7]:
ar3=np.array([1,2])

In [8]:
ar3.ndim

1

In [12]:
ar4=np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])

In [13]:
ar4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]]])

In [14]:
ar4.ndim

4

In [15]:
ar4[0,0,0,0]

1

In [ ]:
#in 0D array we call it as scalar,
#in 1D array we call it as unidimensional and it has 0D array as its element.
#2D array has 1D arrays as its elements often used to represent matrix or  secomd orderd tensors,
#in 3D array the elements are 2D arrays, and ofteb used to represent 3rd orderd tensors.

In [15]:
ar5=np.arange(10,20)

In [16]:
ar5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
ar5.ndim

1

In [12]:
a=np.array([[[1,2,3,4,5,6,7,8,9]]])
#b=np.array([[[1,2,3,4,5,6,7,8,9,10]]])

In [13]:
a,b

(array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]),
 array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]))

In [5]:
a.ndim

3

In [17]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
c.ndim

3

In [80]:
c.shape

(1, 3, 3)

In [75]:
c[:,:3:2]


array([[[1, 2, 3],
        [7, 8, 9]]])

In [76]:
c[:,::]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [77]:
x=np.array([[[2]]])


In [78]:
x

array([[[2]]])

In [79]:
x.shape

(1, 1, 1)

In [61]:
x[0,0,0]

2

In [81]:
ar2=np.array([[[1,2,3,4,5,6,7]]])

In [88]:
ar2[:,:,:2]

array([[[1, 2, 3, 4, 5, 6, 7]]])

In [85]:
ar2.shape

(1, 1, 7)

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
b=a.copy()

In [5]:
b

array([1, 2, 3, 4, 5])

In [6]:
b[0]=6

In [7]:
b

array([6, 2, 3, 4, 5])

In [8]:
a

array([1, 2, 3, 4, 5])

In [11]:
c=a.view()

In [12]:
c

array([1, 2, 3, 4, 5])

In [13]:
c[0]=7

In [14]:
c

array([7, 2, 3, 4, 5])

In [15]:
a

array([7, 2, 3, 4, 5])